vim.fn.sign_define("DapBreakpoint", { text = "🛑", texthl = "", linehl = "", numhl = "" })
vim.keymap.set("n", "<F5>", function()
  require("dap").continue()
end)
vim.keymap.set("n", "<F10>", function()
  require("dap").step_over()
end, { desc = "Debugger: step over" })
vim.keymap.set("n", "<F11>", function()
  require("dap").step_into()
end, { desc = "Debugger: step into" })
vim.keymap.set("n", "<F12>", function()
  require("dap").step_out()
end, { desc = "Debugger: step out" })
vim.keymap.set("n", "<leader>b", function()
  require("dap").toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
vim.keymap.set("n", "<leader>B", function()
  require("dap").set_breakpoint()
end, { desc = "Set breakpoint" })
vim.keymap.set("n", "<leader>dr", function()
  require("dap").repl.open()
end, { desc = "Open debugger REPL" })
vim.keymap.set("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Toggle UI" })
