vim.loader.enable()

require("config.globals")
require("config.lazy")
require("config.colorscheme")
require("config.keymap")
require("config.telescope")
require("config.ufo")
require("config.which_key")
require("config.todo_comments")
require("config.notify")
require("config.lualine")
